version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    image: phpfinanzguru
    container_name: phpfinanzguru-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    tty: true
    stdin_open: true